
spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png
server:
  port: 80
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://数据库IP:3306/数据库名?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: 数据库账户
    password: 数据库密码
    type: com.alibaba.druid.pool.DruidDataSource
  profiles: pro
logging:
  level:
    root: warn
  file:
    name: log/blog-pro.log

mybatis:
  type-aliases-package: com.zwy.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true




